# Generated by Django 5.0.6 on 2024-06-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Naipes', 'Naipes'), ('Uno', 'Uno'), ('Golpe', 'Golpe')], max_length=255),
        ),
    ]
