# Generated by Django 5.0.6 on 2024-06-22 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_types', '0002_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
