# Generated by Django 5.0.6 on 2024-09-15 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_types', '0004_alter_challange_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challange',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='app_types.type'),
        ),
    ]
